### PR TITLE
implementation of generic A-Star path searching algorithm

### PR DESCRIPTION
**Pull request by Fmezia**
Pathfinding Visualizer application that visualizes graph based search algorithms used to find the shortest path.

### CODE REVIEW

**Comment by Fmezia** [comment]
Hello , this is an implementation of A star that I think will enrich the project given the importance of the A star algorithm. can you check and tell me if it's good

**Comment by khalilDerras** [comment]
Hello , Thank you for contributing to my project ,
yes, indeed A star is a very used algorithm in different areas.
Did you test your implementation ?

**Comment by khalilDerras** [comment]
Hello, Thank you for contributing to my project, yes, indeed A star is a very used algorithm in different areas. Did you test your implementation?

**Comment by Fmezia** [comment]
yes, you check it also

**Comment by khalilDerras** [comment]
Cool , i will merge your work then !

**Comment by khalilDerras** [comment]
Thank you a lot for contributing to my project , looking forward to more great contributions from you !

**Comment by Zimmi48** [comment]
For your information, you might consider reverting this PR from your project given that its content was copied (without attribution) from somewhere on the internet (e.g., it can be found almost identical [here](https://stackoverflow.com/questions/63272601/problem-with-exploring-unexplored-nodes-astar-python)).

**Comment by khalilDerras** [comment]
Hello Zimmi48 , Thanx for ur comment , it's flattering that people are interesting in a project that i did for fun , although , i don't mind keeping the changes as long as it's functional even if they're copied (i don't consider copying code from stackoverflow stealing if that's the case we need to arrest all the software engineers lol )

**Pull request merged**
